language: java
before_install:
- git clone https://git@github.com/levilime/tygron.git
- cd tygron
- git checkout setuptravis
install:
- mvn -pl "!doc" install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test -Duser="$email" -Dpwd="$password"
- cd ..
- mv tygron/environment/target/tygronenv-*-jar-with-dependencies.jar .
# make app.properties through travis before script start, needed for user validation
before_script:
- mkdir target
- cd target
- (echo user="$email" & echo pwd="$password" ) > app.properties
- cd ..
script:
# run the Goal Test with a 60s timeout
- timeout 60 java -cp com.github.goalhub.runtime.jar-with-dependencies_2.0.2.20160418123535.jar goal.tools.Run test.test2g -v > result.txt
#if there is a test failed then the build fails
- grep "test failed:" result.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" result.txt && echo 0 || $?
jdk:
- oraclejdk8
