language: java
script:
# run the Goal Test with a 60s timeout
- timeout 60 java -cp com.github.goalhub.runtime.jar-with-dependencies_2.0.2.20160418123535.jar goal.tools.Run test.test2g -v > result.txt
#if there is a test failed then the build fails
- grep "test failed:" result.txt && set -o pipefail || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" result.txt && echo 0 || set -o pipefail
jdk:
- oraclejdk8
