language: java
before_install:
- git clone https://git@github.com/levilime/tygron.git
- cd tygron
install:
# build the connector, testing of the connector is done in the tygron repo CI.
- mvn -pl "!doc" install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- cd ..
# move generated env jar to the same folder as the test file(s)
- mv tygron/environment/target/tygronenv-*-jar-with-dependencies.jar .

# make app.properties through travis before script start, needed for user validation
before_script:
- mkdir target
- cd target
- (echo user="$email" & echo pwd="$password" ) > app.properties
- cd ..
script:
# run the Goal Test with a 60s timeout
- timeout 60 java -cp com.github.goalhub.runtime.jar-with-dependencies_2.0.2.20160418123535.jar goal.tools.Run Municipality/test.test2g -v > result.txt || echo 0
# print the test output
- cat result.txt
# if there is a test failed then the build fails
- grep "test failed:" result.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" result.txt && echo 0 || $?
jdk:
- oraclejdk8
